import Link from "next/link";
import { Sparkles, Bot, GitBranch, Globe, ShieldCheck } from "lucide-react";

export default function Footer() {
  return (
    <footer className="border-t border-slate-800/80 bg-slate-950 text-slate-400 text-sm">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
          {/* Col 1 */}
          <div className="space-y-4 md:col-span-1">
            <div className="flex items-center space-x-2">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-tr from-indigo-500 to-purple-600 flex items-center justify-center">
                <Sparkles className="w-4 h-4 text-white" />
              </div>
              <span className="font-bold text-white tracking-tight text-lg">
                NEXUS<span className="gradient-text">HACK</span>
              </span>
            </div>
            <p className="text-xs text-slate-400 leading-relaxed">
              The ultimate AI hackathon platform powered by intelligent document search and verifiable document intelligence.
            </p>
            <div className="flex items-center space-x-3 text-slate-400">
              <a href="#" className="hover:text-indigo-400 transition-colors" title="Repository"><GitBranch className="w-4 h-4" /></a>
              <a href="#" className="hover:text-indigo-400 transition-colors" title="Website"><Globe className="w-4 h-4" /></a>
            </div>
          </div>

          {/* Col 2 */}
          <div>
            <h4 className="font-semibold text-white mb-3 text-xs uppercase tracking-wider">Navigation</h4>
            <ul className="space-y-2 text-xs">
              <li><Link href="/" className="hover:text-white transition-colors">Landing Page</Link></li>
              <li><Link href="/hackathon" className="hover:text-white transition-colors">Hackathon Overview</Link></li>
              <li><Link href="/chat" className="hover:text-white transition-colors">AI Assistant</Link></li>
              <li><Link href="/dashboard" className="hover:text-white transition-colors">Participant Dashboard</Link></li>
            </ul>
          </div>

          {/* Col 3 */}
          <div>
            <h4 className="font-semibold text-white mb-3 text-xs uppercase tracking-wider">Tracks & Categories</h4>
            <ul className="space-y-2 text-xs">
              <li><span className="hover:text-white transition-colors">Generative AI & Intelligent Search</span></li>
              <li><span className="hover:text-white transition-colors">FinTech & DeFI Analytics</span></li>
              <li><span className="hover:text-white transition-colors">Healthcare & MedTech</span></li>
              <li><span className="hover:text-white transition-colors">Open AI Innovation</span></li>
            </ul>
          </div>

          {/* Col 4 */}
          <div className="space-y-3">
            <h4 className="font-semibold text-white mb-1 text-xs uppercase tracking-wider">AI Trust & Security</h4>

            <div className="p-3 rounded-xl bg-slate-900/90 border border-slate-800 text-xs text-slate-300 flex items-start space-x-2">
              <ShieldCheck className="w-5 h-5 text-emerald-400 shrink-0 mt-0.5" />
              <span>Answers generated by our assistant are grounded in verified document sources with citation tracking.</span>
            </div>
          </div>
        </div>

        <div className="mt-12 pt-6 border-t border-slate-900 flex flex-col md:flex-row items-center justify-between text-xs text-slate-500">
          <p>© 2026 NEXUSHACK Platform. Senior Developer Production Architecture.</p>
          <p className="mt-2 md:mt-0 font-mono">FastAPI + Next.js + SQLite/pgvector</p>
        </div>
      </div>
    </footer>
  );
}
